version: '3.8'

services:
  spark:
    build:
      context: ./services/spark
    ports:
      - "8081:8080"
  
  minio:
    build:
      context: ./services/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123

  kafka:
    build:
      context: ./services/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  hdfs:
    build:
      context: ./services/hdfs
    ports:
      - "50070:50070"

  nifi:
    build:
      context: ./services/nifi
    ports:
      - "8080:8080"

networks:
  default:
    driver: bridge

volumes:
  minio_data:
  kafka_data:
  hdfs_data: